apiVersion: aaq.kubevirt.io/v1alpha1
kind: ApplicationsResourceQuota
metadata:
  name: example-resource-quota
spec:
  hard:
    services: "5"
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gi