apiVersion: aaq.kubevirt.io/v1alpha1
kind: ClusterAppsResourceQuota
metadata:
  name: example-resource-quota
spec:
  quota:
    hard:
      pods: "10"
      secrets: "20"
      requests.cpu/vmi: "1"
      requests.memory/vmi: 1Gi
      requests.instances/vmi: "10"
  selector:
    annotations: null
    labels:
      matchLabels:
        name: example
