apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector: {} # An empty selector means no pods are targeted.
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Replace with the port your service should listen on
